### ISSUE TITLE
Was it hard to show working example?

### ISSUE THREAD

**Issue by kodekrendel** [leftstick/vue-expand-ball#1]
I wonder, what was your intentions when you show example on gif, not actually working code?

**Comment by leftstick** [comment]
`gif` is a good way to demonstrate a series of actions, in this case: `click to expand/collapse`, `draggable`. I want to simply show what this module can do.

Working example is not hard of course, actually i put it at: [document](https://leftstick.github.io/vue-expand-ball/#/apidoc?api=expand-ball). But since it's `draggable` and available in the whole view, i am not sure it's strong enough to attract readers' attention.
